### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by olivbrau** [msteiger/jxmapviewer2#108]
Does anyone know how to implement fractional zoom? (like in Leaflet)
I've tried to think about it, but don't know yet the best way to do it.
Thanks

**Comment by msteiger** [comment]
I thought about it for a while and I believe that it's difficult to realize. You can zoom the tiles, of course even with built-in Swing methods. See [AffineTransform](https://docs.oracle.com/javase/8/docs/api/java/awt/geom/AffineTransform.html) on how to scale images (down).
Probably you will still see visual glitches, because the pre-rendered tiles contains text and it might look distorted. But maybe worth a try.
One alternative would be pulling vector tiles from OMS instead and draw them directly. This would give much higher quality and control over things are shown. I don't know what would be needed to get them though.

**Comment by olivbrau** [comment]
Hi,
Thanks for your answer.
As you say the best way to do is working with vector data.
But in fact, as render quality is concerned, tile scaling is not a real
problem for me.

I think the good way is to make a big "collage" and then to scale (instead
of scaling each tile individually) to avoid artifacts on edges.It is slower
since the tile arrive in sequence ...

My problem is just to find formula to find the coordinates to draw the
scaled images and the formula to convert from screen coordinate to long/lat.

Olivier

Le dim. 21 mars 2021 à 09:01, Martin Steiger ***@***.***> a
écrit :

**Comment by msteiger** [comment]
I think the easiest is to just draw everything as before and use an `AffineTransform` to scale the final image just before rendering it to the size that you want. Alternatively, you can scale them individually as you suggest. The coordinate transformation is done in those two classes here:
https://github.com/msteiger/jxmapviewer2/tree/master/jxmapviewer2/src/main/java/org/jxmapviewer/viewer/util
Hope that helps!

**Comment by msteiger** [comment]
Closing this from age ...
