### ISSUE TITLE
zoomToBestFit centers to wrong position

### ISSUE THREAD

**Issue by d4rnok** [msteiger/jxmapviewer2#63]
As mentioned in the last comment to issue https://github.com/msteiger/jxmapviewer2/issues/18
`zoomToBestFit()` still centers to a wrong position. 

In my opinion there is something wrong with `public void setCenter(Point2D center)` in relation finding the right zoom level top down from the maximum zoom level. If the map has the same width and lenght it works fine. But if they are different you get a wrong center position of the map.

My workaround is not to set the max. ZoomLevel in `zoomToBestFit()` . But this does not solve the original problem.

```
        // set map to maximum zoomed out
        setZoom(info.getMaximumZoomLevel()-1);
```

**Comment by Mouseviator** [comment]
Hi,

I recently discovered this great map component, using it in my app and now facing the same issue. I found out, that it happens when the height of the map component grows above certain value. Than, when the height of the map component is enough, this code:

```
Rectangle newVP = calculateViewportBounds(center);
if (newVP.getY() < 0)
{
	centerY = viewportHeight / 2;
}
```

starting at line **576** (_JXMapViewer.java_) which controls if we did not pan the map over the top edge will take effect. And it will shift the Y coordinate of the center position previously computed in the **zoomToBestFit** method. The **setCenter** method is called from the **setZoom** method, which is called from **zoomToBestFit** which continuously tries to zoom in until finding the right zoom. But when the center point gets shifted, it of course continues to zoom on the wrong center point.

So my fix for this was to put this code after line **711** and **748** in the **zoomToBestFit** method in the _JXMapViewer.java_ (so after both calls to setZoom):

```
        //check that center position did not change due to breaking pan constraints
        GeoPosition currCenter = getCenterPosition();
        if (Math.abs(centre.getLatitude() - currCenter.getLatitude()) > 1 ||
            Math.abs(centre.getLongitude() - currCenter.getLongitude()) > 1) {
            System.out.println("Center position shifted more than 1 degree! Reseting to first calculated value!");
            setCenterPosition(centre);
        }
```

	
In the added code I check if the position shifted more than one degree and if it does, I recenter to the originally computed center point. The System.out.println were used to see the behavior and I would remove them. Also, question is what is faster, to check if the center did shift or just call setCenterPosition(centre); after each zoom.

**Comment by msteiger** [comment]
Thanks for reporting! I will look into it as soon as I can.

**Comment by msteiger** [comment]
Can you please provide an example that illustrates the problem? Preferably based on [Sample2](https://github.com/msteiger/jxmapviewer2/blob/master/examples/src/sample2_waypoints/Sample2.java) (it uses zoomToBestFit).

I think I have a fix, but I would like to test it first.

**Comment by Mouseviator** [comment]
Hi,

yes. It is quite easy to reproduce. I just added this code into Sample2.java (after line 62 where is the initial call to zoomToBestFit):

```                
                frame.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        if (e.getButton() == MouseEvent.BUTTON3) {
                            mapViewer.zoomToBestFit(new HashSet<GeoPosition>(track), 0.7);
                        }
                    }

                    @Override
                    public void mousePressed(MouseEvent e) {                        
                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {                        
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {                        
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {                        
                    }
                });
```

So that you can call zoomToBestFit after clicking right mouse button. I run the example, resize the window a little bit (or maximizing it), right click on the map and it will center on the wrong place.

**Comment by msteiger** [comment]
Thank you. Tested and confirmed that it fixes the issue.
