### ISSUE TITLE
Can we add search location bar functionality via jxmapviewer2

### ISSUE THREAD

**Issue by ooxaam** [msteiger/jxmapviewer2#69]
Its a guidance request, instead of an Issue. I want to add search location functionality in the desktop version of Jxmapviewer ( similar to available at OpenStreetmap site  https://www.openstreetmap.org )
Can you kindly guide, what will be the steps for achieving this goal.

Cheers.

**Comment by msteiger** [comment]
Are we talking about search functionality for locations? The jxmapviewer2 only paints pictures on the canvas, so it doesn't know anything about the content.

Since OSM is free and open-source, you might be able to connect to their REST API and use the search functionality from there. Maybe this is a good starting point: https://wiki.openstreetmap.org/wiki/Frameworks

**Comment by ooxaam** [comment]
Thanks @msteiger for the quick response. It helped.
